version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/vectorstore:/app/vectorstore
    env_file:
      - backend/.env
    environment:
      - EMBEDDING_MODEL=all-MiniLM-L6-v2
      - EMBEDDING_DEVICE=cpu

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "5173:80" # Nginx serves on port 80 in the container
    # Volumes removed to serve static content built by frontend/Dockerfile
    env_file:
      - frontend/.env
    depends_on:
      - backend